//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayId { get; set; }
        public string kaySorId { get; set; }
        public string kaySecId { get; set; }
    
        public virtual Cevap Cevap { get; set; }
        public virtual Soru Soru { get; set; }
    }
}
